productId: respawn
productName: Respawn
productDescription: Respawns you at your last death location.
price: 10000
callbackDelivery: ALLOW_OFFLINE_DELIVERY
namespaceId: studio-examples
repeatablePurchase: true